name: pre-merge check

on:
  push:
    branches:
      - master
      - develop
      - features/sprint*
      - stable_v*
  pull_request:
    branches:
      - master
      - develop
      - features/sprint*
      - stable_v*

jobs:
  rust-test:
    name: rust test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, macos-15, ubuntu-24.04]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: build
        with:
          command: build
      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
